services:
    shopery.error.exception_listener:
        class: Shopery\Bundle\ErrorBundle\Listener\ExceptionListener
        arguments: ~
        tags:
            -   name: kernel.event_listener
                event: kernel.exception
                method: onKernelException
